----SET
----  TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
----SELECT
----  u.*,
----  (
----    SELECT
----      COUNT(*)
----    FROM
----      Invoices
----    WHERE
----      DriverId = u.Id
----      AND Status IN (2, 5)
----  ) CInvoice,
----  (
----    SELECT
----      providerId,
----      phoneNumber,
----      displayName,
----      uid,
----      email
----    FROM
----      Logins
----    WHERE
----      UserId = u.Id FOR JSON PATH
----  ) Logins,
----  (
----    SELECT
----      COUNT(1) as Invoice,
----      SUM(
----        case
----          when ServiceId in ('truck') then Total / 20
----          else CASE
----            WHEN Created < '2021/04/15' THEN TOTAL / 10
----            ELSE Total * 15 / 100
----          END
----        end
----      ) as
----    Minus
----,
----    SUM(Weight) Weight,
----    SUM(Distance) Distance,
----    SUM(Price) Price,
----    SUM(DiscountPrice) Plus
----    FROM
----      Invoices
----    WHERE
----      DriverId = u.Id
----      and Status in (7, 11) FOR JSON PATH
----  ) DriverSum,
----  (
----    SELECT
----      *
----    FROM
----      UserRoles
----    WHERE
----      UserId = u.Id FOR JSON PATH
----  ) UserRole,
----  (
----    SELECT
----      *
----    FROM
----      UserDocument
----    WHERE
----      UserId = u.Id FOR JSON PATH
----  ) Document,
----  (
----    SELECT
----      us.*
----    FROM
----      UserServices us
----    WHERE
----      us.UserId = u.Id
----      AND IsActive = 1 FOR JSON PATH
----  ) Services,
----  (
----    SELECT
----      ua.Id,
----      p.place_id,
----      p.Address,
----      p.Province,
----      ua.Active
----    FROM
----      UserAddresss ua
----      LEFT JOIN Places p ON p.place_id = ua.PlaceId
----    WHERE
----      UserId = u.Id FOR JSON PATH
----  ) Address,
----  (
----    SELECT
----      c.ContractId,
----      c.PlaceStartId,
----      p.Latitude,
----      p.Longitude,
----      p.Address
----    FROM
----      Contracts c
----      LEFT JOIN Places p ON p.place_id = c.PlaceStartId
----    WHERE
----      c.OwnerId = u.Id
----      AND c.IsActive = 1 FOR JSON PATH
----  ) Contracts
----FROM
----  Users u
---- USER LIST
--SET
--  TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
--SELECT
--  COUNT(1)
--FROM
--  Users
--WHERE
--  (
--    SearchValue LIKE @Filter
--    OR PhoneNumber LIKE @Filter
--    OR Email LIKE @Filter
--    OR Id = @Filter
--  )
--SELECT
--  u.*,
--  (
--    SELECT
--      Count(1)
--    FROM
--      Logins l
--    WHERE
--      l.UserId = u.Id
--  ) Login,
--  (
--    SELECT
--      Count(1)
--    FROM
--      Notifications l
--    WHERE
--      l.OwnerId = u.Id
--  ) Notification,
--  (
--    SELECT
--      Count(1)
--    FROM
--      Notifications l
--    WHERE
--      l.OwnerId = u.Id
--      and l.IsActive = 1
--      and l.[Delete] is null
--  ) NotificationActive,
--  (
--    SELECT
--      Count(1)
--    FROM
--      Notifications l
--    WHERE
--      l.OwnerId = u.Id
--      and l.IsActive = 0
--      and l.[Delete] is not null
--  ) NotificationDeActive,
--  (
--    SELECT
--      Count(1)
--    FROM
--      UserDocument l
--    WHERE
--      l.UserId = u.Id
--  ) Document,
--  (
--    SELECT
--      Count(1)
--    FROM
--      UserServices l
--    WHERE
--      l.UserId = u.Id
--  ) Service,
--  (
--    SELECT
--      Count(1)
--    FROM
--      UserServices l
--    WHERE
--      l.UserId = u.Id
--      and l.IsActive = 1
--  ) ServiceActive,
--  (
--    SELECT
--      Count(1)
--    FROM
--      UserRoles l
--    WHERE
--      l.UserId = u.Id
--  ) Employee,
--  (
--    SELECT
--      Count(1)
--    FROM
--      UserLocations l
--    WHERE
--      l.UserId = u.Id
--  ) Locations
--FROM
--  (
--    SELECT
--      Id,
--      DisplayName,
--      PhotoURL,
--      PhoneNumber,
--      Money,
--      LastCreated,
--      LastModify,
--      Email,
--      RefUser,
--      Block,
--      Free,
--      Score
--    FROM
--      Users
--    WHERE
--      (
--        SearchValue LIKE @Filter
--        OR PhoneNumber LIKE @Filter
--        OR Email LIKE @Filter
--        OR Id = @Filter
--      )
--    ORDER BY
--      LastModify DESC OFFSET @Skip ROWS FETCH NEXT @PageSize ROWS ONLY
--  ) u