export const ROUTES = {
  LANDING: '/',
  DetailLink: dbId => '/' + dbId,
  About: '/gioi-thieu',
  Project: '/du-an',
  News: '/tin-tuc',
  Contact: '/lien-he',
  NewsLink: newsId => '/tin-tuc/' + newsId,
  Recuitment: '/tuyen-dung',
  ProjectLink: dbId => '/du-an/' + dbId,
  Admin: '/admin',
  AdminConfig: '/admin/cau-hinh',
  AdminBanner: '/admin/banner',
  AdminBannerLink: bannerId => '/admin/banner/' + bannerId,
  AdminServices: '/admin/dich-vu',
  AdminServicesLink: serviceId => '/admin/dich-vu/' + serviceId,
  AdminPartner: '/admin/doi-tac',
  AdminPartnerLink: partnerId => '/admin/doi-tac/' + partnerId,
  AdminProjects: '/admin/du-an',
  AdminProjectLink: dbId => '/admin/du-an/' + dbId,
  AdminReason: '/admin/ly-do',
  AdminReasonLink: dbId => '/admin/ly-do/' + dbId,
  AdminTags: '/admin/tag',
  AdminTagLink: tagId => '/admin/tag/' + tagId,
  AdminVideos: '/admin/video',
  AdminVideoLink: videoId => '/admin/video/' + videoId,
  AdminTeam: '/admin/thanh-vien',
  AdminTeamLink: teamId => '/admin/thanh-vien/' + teamId,
  AdminTagsBlog: '/admin/the-bai-viet',
  AdminTagBlogLink: tagId => '/admin/the-bai-viet/' + tagId,
  AdminBlogs: '/admin/blog',
  AdminBlogLink: blogId => '/admin/blog/' + blogId,
  AdminBlogsHL: '/admin/blog/noi-bat',
  AdminBlogHLLink: blogHLId => '/admin/blog/noi-bat/' + blogHLId,
  AdminAccounts: '/admin/phan-quyen',
  AccountDetailLink: userId => '/admin/phan-quyen/' + userId
};
